name: 'github-package-version-bumper'
description: 'Allows you to automatically bump version with tag creation'
author: 'blaadje'
inputs:
  github-token:
    description: GitHub authentication token
    required: true
runs:
  using: 'node12'
  main: 'index.js'
