name: 'Your name here'
description: 'Provide a description here'
author: 'Your name or organization here'
inputs:
  github-token:
    description: GitHub authentication token
    required: true
runs:
  using: 'node12'
  main: 'lib/main.js'
